=== curioustorvald/Terrarum/btexdoc.dtd
<!ENTITY nbsp "&#xA0;">
<!ENTITY money "&#xA4;">

<!ENTITY % special.extra "img">
<!ENTITY % special.basic "br | span">
<!ENTITY % special "%special.basic; | %special.extra;">
<!ENTITY % fontstyle.extra "big | small | font | basefont">
<!ENTITY % fontstyle.basic "tt | i | b | u | s | strike ">
<!ENTITY % fontstyle "%fontstyle.basic; | %fontstyle.extra;">
<!ENTITY % inlinelogo "btex | tex | latex">
<!ENTITY % inline "a | %special; | %fontstyle; | code | bucks | %inlinelogo; | index | var">
<!ENTITY % Inline "(#PCDATA | %inline;)*">
<!ENTITY % Text "CDATA">
<!ENTITY % TextAlign "align (left|center|right|justify) #IMPLIED">
<!ENTITY % HeadingAttr
"hide CDATA #IMPLIED
 alt %Text; #IMPLIED">

<!ENTITY % BTeXcover "cover (hardcover|none) #IMPLIED">
<!ENTITY % BTeXinner "inner (standard) #IMPLIED">
<!ENTITY % BTeXpapersize "papersize (standard) #IMPLIED">
<!ENTITY % BTeXdefs "defs (mail|giro|examination) #IMPLIED">

<!ENTITY % id-only "id ID #REQUIRED">
<!ENTITY % key-value
"key CDATA #REQUIRED
 value CDATA #REQUIRED">
<!ENTITY % coreattrs
"id          ID             #IMPLIED
 class       CDATA          #IMPLIED
 title       %Text;         #IMPLIED">

<!ENTITY % attrs "%coreattrs;">

<!ENTITY % heading "part | chapter | section | subsection">
<!ENTITY % lists "ul | ol">
<!ENTITY % blocktext "pre | anonbreak | pbox | center | fullpagebox">
<!ENTITY % block "p | %heading; | %lists; | %blocktext;">
<!ENTITY % Flow "(#PCDATA | %block; | %inline;)*">

<!ENTITY % ULStyle "(disc|square|circle)">
<!ENTITY % Number "CDATA">
<!ENTITY % LIStyle "CDATA">

<!ELEMENT btexdoc (cover?,tocpage?,manuscript,indexpage?)>
<!ATTLIST btexdoc
        %BTeXcover;
        %BTeXinner;
        %BTeXpapersize;
        %BTeXdefs;
        >

<!-- COVER tag specification -->
<!ELEMENT cover (title?, subtitle?, author?, edition?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT edition (#PCDATA)>

<!-- TOC-like tag specification -->
<!ELEMENT tocpage (tableofcontents)>
<!ATTLIST tocpage title %Text; #IMPLIED>
<!ELEMENT indexpage (tableofindices)>
<!ATTLIST indexpage title %Text; #IMPLIED>

<!-- MANUSCRIPT tag specification -->
<!ELEMENT manuscript %Flow;>
<!ELEMENT fullpagebox %Flow;>
<!ELEMENT pbox %Inline;>
<!ATTLIST pbox %attrs; %TextAlign;>

<!ELEMENT part %Inline;>
<!ATTLIST part %HeadingAttr;>
<!ELEMENT chapter %Inline;>
<!ATTLIST chapter %HeadingAttr;>
<!ELEMENT section %Inline;>
<!ATTLIST section %HeadingAttr;>
<!ELEMENT subsection %Inline;>
<!ATTLIST subsection %HeadingAttr;>


<!-- self-closing tags -->
<!ELEMENT tableofcontents EMPTY>
<!ELEMENT tableofindices EMPTY>
<!ELEMENT anonbreak EMPTY>
<!ELEMENT newpage EMPTY>
<!ELEMENT btex EMPTY>
<!ELEMENT latex EMPTY>
<!ELEMENT tex EMPTY>
<!ELEMENT var EMPTY>
<!ATTLIST var %id-only;>
<!ELEMENT pair EMPTY>
<!ATTLIST pair %key-value;>
<!ELEMENT index EMPTY>
<!ATTLIST index %id-only;>

<!-- inherited from HTML -->
<!ELEMENT p %Inline;>
<!ATTLIST p %attrs; %TextAlign;>
<!ELEMENT span %Inline;>
<!ATTLIST span %attrs;>
<!ELEMENT emph %Inline;>
<!ELEMENT itemname %Inline;>
<!ELEMENT targetname %Inline;>
<!ELEMENT code %Inline;>
<!ELEMENT bucks %Inline;>
<!ELEMENT br EMPTY>
<!ELEMENT ul (li)+>
<!ATTLIST ul
        %attrs;
        type        %ULStyle;     #IMPLIED
        compact     (compact)     #IMPLIED
        >
<!ENTITY % OLStyle "CDATA">
<!ELEMENT ol (li)+>
<!ATTLIST ol
        %attrs;
        type        %OLStyle;      #IMPLIED
        compact     (compact)      #IMPLIED
        start       %Number;       #IMPLIED
        >
<!ELEMENT li %Flow;>
<!ATTLIST li
        %attrs;
        type        %LIStyle;      #IMPLIED
        value       %Number;       #IMPLIED
        >

=== curioustorvald/Terrarum/assets/mods/basegame/books/btex_ko.xml
<!DOCTYPE btexdoc SYSTEM "btexdoc.dtd">
<btexdoc cover="hardcover" inner="standard" papersize="standard">
    <macrodef>
        <pair key="thepart" value="제%1$s부"/>
        <pair key="thechapter" value="%1$s장"/>
    </macrodef>
    <cover>
        <title>문자를 모아 책을 찍어내어 엮는 머나먼 여정으로의 소개</title>
        <subtitle>책 쓰고 찍어내는 법</subtitle>
        <author>Terran Publishing</author>
        <edition>시험판</edition>
    </cover>

    <tocpage title="목차"><tableofcontents/></tocpage>

    <manuscript>
        <part type="1">책</part>

        <chapter>책이란 무엇인가</chapter>

        <p>본 견본은 책 조판 언어의 예시를 위해 제작되었다.</p>

        <section hide="1">책이란 정말 무엇인가</section>

        <p><index id="책"/>책 조판 시스템에서 책이란 페이지 번호와 그림과 <a href="하이퍼링크">하이퍼링크</a>와 같은 요소를 포함하여 가독성 좋게 편집된 글의 뭉치를 말한다.</p>
        <p>책은 ‘엮인’ 글로 취급되어 두 페이지가 한번에 보여진다.</p>

        <chapter>타자기를 사용한 집필</chapter>

        <p><index id="타자기"/>타자기는 글 쓰기의 시작을 빠르고 편리하게 해 준다. 타자기를 클릭하면 바로 작성이 가능하다.</p>
        <p>하지만 타자기를 사용할 때는 여러 문자 사용 불가, 사진 첨부 불가, 하이퍼링크 사용 불가, 너덜너덜해 못생긴 문단과 같은 크나큰 단점이 따라온다.</p>
        <p>타자기로 찍은 문서는 ‘엮이지 않은’ 글로 취급되어 한번에 한 페이지만 보여진다.</p>
        <p>위와 같은 이유로 타자기로는 책다운 책을 만들 수 없다.</p>

        <chapter>출판사와 인쇄소를 이용한 집필</chapter>

        <p>출판사를 통하면 진짜배기 책의 모든 장점을 담은 책다운 책을 고작 한 권도 아닌 여러 권을 원하는 만큼 찍어낼 수 있다.</p>
        <p>책을 인쇄하려면 원고를 출판사로 보내야 한다. 책을 찍어내기 위한 원고는 <btex/>이라는 특수한 언어로 작성되어야 한다.</p>
        <p><btex/>을 통하며 책 전체의 생김새를 간단히 기술할 수 있다. 사용할 수 있는 스타일은 조판 시스템이 지원하는 범위 안에서 제약이 없다. 타자기로 찍어낸 듯한 글도 원한다면 얼마든지 인쇄되도록 할 수 있다.</p>


        <part type="1"><btex/></part>

        <chapter>소개</chapter>

        <p><index id="btex 언어"/><btex/>(발음: [비ː텍])은 <latex/>과 유사하게 설계된 XML 기반의 마크업 언어이다.
            <btex/>은 세세한 스타일 정의문과 조판 설정을 추상화하여, 글을 쓰면서 <latex/> 매크로를 디버깅하는 등의 일 없이 글쓰기에 집중할 수 있도록 설계되었다. 다만 이러한 이유로 미리 정의된 스타일을 뜯어고치는 것은 어렵다.</p>
        <p><btex/> 문서는 다음의 다섯 부분으로 나뉘어진다. <a href="btexdoc">스타일 정의문</a>,
            <a href="표지 정의문">표지 정의문</a>, <a href="목차 정의문">목차 정의문</a>, <a href="원고">원고</a>, <a href="색인 페이지">색인 페이지</a>. 이 중 스타일 정의문과 원고는 필수로 존재하여야 하는 부분이다.</p>


        <chapter>스타일 정의문</chapter>

        <p><index id="btexdoc"/>스타일 정의문은 <btex/> 문서의 가장 첫 부분이다. 스타일 정의문의 구조는 다음과 같다.</p>

        <callout align="left" class="code"><index id="btexdoc (태그)"/>&lt;btexdoc cover="hardcover" inner="standard" papersize="standard"&gt;
        </callout>

        <p><code>btexdoc</code> 태그는 다음의 속성을 지원한다.</p>
        <ul>
            <li><code>cover</code> — 표지의 스타일을 지정함. 지원하는 값: <code>hardcover</code>, <code>none</code></li>
            <li><code>inner</code> — 내용의 스타일을 지정함. 지원하는 값: <code>standard</code>, <code>typewriter</code></li>
            <li><code>papersize</code> — 판형을 지정함. 지원하는 값: <code>standard</code></li>
        </ul>

        <chapter>표지 정의문</chapter>

        <p><index id="표지 정의문"/><code>cover</code> 태그는 책의 표지를 지정한다. 표지가 없는 책이라면 이 부분은 생략 가능하다. 표지 정의문의 구조는 다음과 같다.</p>
        <callout align="left" class="code"><index id="cover (태그)"/><index id="title (태그)"/><index id="subtitle (태그)"/><index id="author (태그)"/><index id="edition (태그)"/>&lt;cover hue="358"&gt;<br/>
            　　&lt;title&gt;책 제목&zwsp;&lt;/title&gt;<br/>
            　　&lt;subtitle&gt;필요한 경우 부제목&zwsp;&lt;/subtitle&gt;<br/>
            　　&lt;author&gt;누가 이 책을 집필하였는가&zwsp;&lt;/author&gt;<br/>
            　　&lt;edition&gt;필요한 경우 판본 정보&zwsp;&lt;/edition&gt;<br/>
            &lt;/cover&gt;
        </callout>
        <p>이 중 <code>title</code> 태그만이 필수 태그이다. 표지의 문구는 글자간 간격이 넓게 인쇄된다. 책 제목은 두배 큰 크기로 인쇄된다.</p>
        <p>표지의 색깔은 <code>hue</code> 속성을 사용해 바꿀 수 있다. 0에서 360 사이의 숫자를 사용할 수 있다.</p>


        <chapter>목차 정의문</chapter>

        <p><index id="목차 정의문"/>목차 페이지의 내용은 원고를 읽어 자동으로 채워진다. 목차 정의문의 구조는 다음과 같다.</p>

        <callout align="left" class="code"><index id="tocpage (태그)"/>&lt;tocpage title="목차 혹은 필요한 다른 제목"&gt;&zwsp;&lt;tableofcontents/&gt;&zwsp;&lt;/tocpage&gt;
        </callout>

        <p><code>title</code> 속성은 목차 페이지의 장제목을 지정한다. 지정하지 않았으면 “Table of Contents”가 인자된다.</p>
        <p><code>&lt;tableofcontents/&gt;</code> 태그는 조판 시스템이 내부적으로 사용하는 태그이다.</p>


        <chapter>원고</chapter>

        <p><index id="원고"/><index id="태그 목록"/>원고는 실제 책의 본문이 담긴 부분을 말한다. 본문에는 다음의 태그를 사용할 수 있다.</p>
        <ul>
            <li><index id="part (태그)"/><code>part</code> — inserts part separation page to your book</li>
            <li><index id="chapter (태그)"/><index id="section (태그)"/><code>chapter</code>, <code>section</code> — inserts a new chapter/section. If an alternative name is required on the Table of Contents, the <code>alt</code> attribute can be used. If the chapter/section needs to be hidden on the Table of Contents, add the <code>hide="1"</code> attribute. If the chapter must start on a new page, simply add <code>newpage</code> in front of the chapter tag</li>
            <li><index id="p (태그)"/><code>p</code> — inserts a new paragraph. The body texts must be written inside this tag. All paragraphs will have a 16-pixel indentation, with the following exceptions: first <code>p</code> of the part/chapter/section; first <code>p</code> after <code>br</code>, <code>newpage</code>, <code>callout</code>, <code>ul</code>, <code>ol</code> or <code>anonbreak</code></li>
            <li><index id="span (태그)"/><code>span</code> — allows changing the colour of the texts. The colour must be specified in the <code>colour</code> attribute. Six-digit hex code, three-digit hex code and CSS Colors Level 4 named colours are supported. Note that all the colours will be rounded to the nearest three-digit hex code</li>
            <li><index id="emph (태그)"/><code>emph</code> — is a special case of the <code>span</code> tag. The resulting text will be <emph>red</emph></li>
            <li><index id="itemname (태그)"/><code>itemname</code> — is a special case of the <code>span</code> tag used to highlight the name of the ingame item. The resulting text will be <itemname>blue</itemname></li>
            <li><index id="targetname (태그)"/><code>targetname</code> — is a special case of the <code>span</code> tag used to highlight the name of an arbitrary target or goals. The resulting text will be <targetname>green</targetname></li>
            <li><index id="code (태그)"/><code>code</code> — is a special case of the <code>span</code> tag used to highlight the code element in-line. The resulting text will be <code>surrounded in a grey box</code></li>
            <li><index id="br (태그)"/><code>br</code> — self-closing tag; inserts an anonymous line break</li>
            <li><index id="newpage (태그)"/><code>newpage</code> — self-closing tag; inserts an anonymous page break</li>
            <li><index id="anonbreak (태그)"/><code>anonbreak</code> — self-closing tag; inserts a paragraph break in the text. The break will be in a form of a long straight line on the centre of the text. Useful for typesetting novels</li>
            <li><index id="callout (태그)"/><code>callout</code> — is a paragraph box that holds a text in a grey box, a style similar to the <code>code</code> tag</li>
            <li><index id="ul (태그)"/><index id="li (태그)"/><code>ul</code> — starts an unordered list. List elements are defined using the <code>li</code> tag</li>
            <li><index id="ol (태그)"/><code>ol</code> — starts an ordered list. List elements are defined using the <code>li</code> tag</li>
            <li><index id="fullpagebox (태그)"/><code>fullpagebox</code> — is used to typeset its child tags into a box that fills an entire page, with its contents centred on the page. Must be used after the <code>newpage</code></li>
            <li><index id="btex (태그)"/><code>btex</code> — self-closing tag; inserts an inline form of the <btex/> logo in the text</li>
        </ul>
        <p>스스로 닫는 태그는 하위 내용을 담을 수 없다. 스스로 닫는 태그는, 예를 들어 tagname이라는 태그가 있으면, 다음과 같이 쓴다. <code>&lt;tagname/&gt;</code>.</p>


        <section>장절제목 스타일</section>

        <p>부와 장과 절은 <code>type</code> 속성을 사용해 번호가 찍히는 스타일을 지정할 수 있다. 지원하는 스타일은 다음과 같다.</p>
        <ul>
            <li><code>a</code> — 번호로 알파벳을 사용함 (a, b, c, …)</li>
            <li><code>A</code> — 번호로 알파벳 대문자를 사용함 (A, B, C, …)</li>
            <li><code>i</code> — 번호로 로마 숫자를 사용함 (i, ii, iii, …)</li>
            <li><code>I</code> — 번호로 로마 숫자 대문자를 사용함 (I, II, III, …)</li>
            <li><code>1</code> — 번호를 사용함 (1, 2, 3)</li>
        </ul>
        <p>기본값은, 부는 로마 숫자 대문자, 장과 절은 그냥 번호를 사용한다. “Part I”로 찍히는 것을 “제1절”로 변경하는 등의 심화된 스타일은 <a href="macro definition">매크로 정의문</a>에서 정의할 수 있다.</p>


        <section>문단 스타일</section>

        <p><code>p</code>와 <code>callout</code> 태그는 <code>align</code> 속성을 지원한다. 지원하는 스타일은 다음과 같다.</p>
        <ul>
            <li><code>left</code> — 문단을 좌측정렬함</li>
            <li><code>justify</code> — 문단을 양끝정렬함. 기본값</li>
        </ul>
        <p><code>p</code>, <code>span</code>, <code>callout</code> 태그는 추가로 <code>class="code"</code> 속성을 지원한다. 이 속성이 적용된 문구는 <code>코드꼴(code font)</code>을 사용해 인자된다.</p>


        <section>하이퍼링크</section>

        <p><index id="하이퍼링크"/>하이퍼링크는<code>index</code>와 <code>a</code> 태그를 사용해 적용할 수 있다.</p>
        <ul>
            <li><index id="index (태그)"/><code>index</code> — 링크의 목적지를 정의함. 링크의 이름은 문서 전체에서 유일하여야 하며, <code>id</code> 속성에 작성함</li>
            <li><index id="a (태그)"/><code>a</code> — 태그 내부의 문구를 클릭 가능하게 함. 링크의 목적지는 (index 태그의 id) <code>href</code> 속성에 작성함</li>
        </ul>


        <chapter>색인 페이지</chapter>

        <p><index id="색인 페이지"/>색인 페이지의 내용은 원고를 읽어 자동으로 채워진다.
            문서에 사용된 모든 <code>index</code> 태그가 이 페이지에 인쇄된다. 색인 페이지의 구조는 다음과 같다.</p>

        <callout align="left" class="code"><index id="indexpage (태그)"/>&lt;indexpage title="색인 혹은 필요한 다른 제목"&gt;&zwsp;&lt;tableofindices/&gt;&zwsp;&lt;/indexpage&gt;
        </callout>

        <p><code>title</code> 속성은 색인 페이지의 장제목을 지정한다. 지정하지 않았으면 “Index”가 인자된다.</p>


        <chapter>문서 끝맺기</chapter>

        <p><btex/> 문서는 <code>btexdoc</code> 태그로 시작되었으니, 반드시 같은 태그로 끝나야 한다. <code>&lt;/btexdoc&gt;</code>을 써 넣어 문서를 마무리하자.</p>


        <chapter>마무리</chapter>
